name: Sync to openapi repo of YBA

on:
  workflow_dispatch: {}
  push:
    branches:
      - main2

jobs:
  copy-file:
    name: apiserver - sync to openapi repos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          
      - name: Copy files to another repository
        if: github.ref == 'refs/heads/main'
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'source_dir/file_main.txt'
          destination-username: 'ashutosh-yb'
          destination-repository: 'repo2'
          destination-directory: 'dir/'
          destination-branch: 'main'
          commit-email: 'aanshu@yugabyte.com'
          
      - name: Copy files to another repository
        if: github.ref != 'refs/heads/main'
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'source_dir/file_main.txt'
          destination-username: 'ashutosh-yb'
          destination-repository: 'repo2'
          destination-directory: 'dir/'
          destination-branch: 'repo2branch'
          commit-email: 'aanshu@yugabyte.com'
          
          
