name: Sync to openapi repos

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  copy-file:
    name: apiserver - sync to openapi repos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
          
      - name: Copy files to another repository
        if: github.ref == 'refs/heads/main'
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'source_dir/file2.txt'
          destination-username: 'ashutosh-yb'
          destination-repository: 'repo2'
          destination-directory: 'dir/'
          destination-branch: 'new_branch'
          commit-email: 'aanshu@yugabyte.com'
          
