name: Sync to openapi repos

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  copy-file:
    name: apiserver - sync to openapi repos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Push to repo2 repo main branch
        if: github.ref == 'refs/heads/main'
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source_file: 'hello.txt'
          destination-github-username: 'ashutosh-yb'
          destination-repository-name: 'repo2'
          destination_folder: 'dir'
          user_email: 'ashutosh3194@email.com'
          user_name: 'ashutosh'
          target-branch: ${{ github.ref_name }}
          
